In [1]:
import pandas as pd

import trees
import util

In [2]:
bikes = pd.read_csv("SeoulBikeData.csv")
train, dev = util.split(bikes, [0.8, 0.2], seed=2022)

TARGET = "Rented Bike Count"

In [3]:
dtree = trees.Tree(max_levels=2, verbose=True)

In [4]:
dtree.train(train, TARGET)

Splitting - level 0, node 0, size 7008
Splitting - level 1, node 1, size 3275
Splitting - level 1, node 2, size 3733

In [5]:
print(dtree)

Node: 0, Level: 0, Parent: None, Size: 7008
	Column: Temperature(°C), Type: numeric, Boundary: 12.0
	Target: Rented Bike Count, Pred: 699.2
	Left: 1, Right: 2, Leaf: False
Node: 1, Level: 1, Parent: 0, Size: 3275
	Column: Seasons, Type: categorical, Boundary: Autumn
	Target: Rented Bike Count, Pred: 361.9
	Left: 3, Right: 4, Leaf: False
Node: 2, Level: 1, Parent: 0, Size: 3733
	Column: Hour, Type: numeric, Boundary: 14
	Target: Rented Bike Count, Pred: 995.0
	Left: 5, Right: 6, Leaf: False
Node: 3, Level: 2, Parent: 1, Size: 742
	Column: None, Type: None, Boundary: None
	Target: Rented Bike Count, Pred: 639.4
	Left: None, Right: None, Leaf: True
Node: 4, Level: 2, Parent: 1, Size: 2533
	Column: None, Type: None, Boundary: None
	Target: Rented Bike Count, Pred: 280.7
	Left: None, Right: None, Leaf: True
Node: 5, Level: 2, Parent: 2, Size: 2219
	Column: None, Type: None, Boundary: None
	Target: Rented Bike Count, Pred: 695.0
	Left: None, Right: None, Leaf: True
Node: 6, Level: 2, Parent: 2, Size: 1514
	Column: None, Type: None, Boundary: None
	Target: Rented Bike Count, Pred: 1434.7
	Left: None, Right: None, Leaf: True

In [6]:
preds = dtree.predict(dev)
preds

10      1434.723910
12      1434.723910
17      1434.723910
34      1434.723910
38       695.046417
           ...
8748    1434.723910
8750     695.046417
8754    1434.723910
8757    1434.723910
8759    1434.723910
Length: 1752, dtype: float64

In [7]:
dev.assign(preds = preds)

,Date,Rented Bike Count,Hour,Temperature(°C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(°C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Seasons,Holiday,Functioning Day,preds
10,1/12/2017,339,10,-3.5,24,1.2,1996,-21.2,0.65,0.0,0.0,Winter,No Holiday,Yes,1434.723910
12,1/12/2017,449,12,1.7,23,1.4,2000,-17.2,1.11,0.0,0.0,Winter,No Holiday,Yes,1434.723910
17,1/12/2017,555,17,0.8,58,1.6,2000,-6.5,0.08,0.0,0.0,Winter,No Holiday,Yes,1434.723910
34,2/12/2017,334,10,-0.4,57,1.6,1309,-7.8,0.80,0.0,0.0,Winter,No Holiday,Yes,1434.723910
38,2/12/2017,611,14,7.3,35,1.3,1955,-7.1,0.99,0.0,0.0,Winter,No Holiday,Yes,695.046417
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8748,30/11/2018,720,12,6.6,35,1.3,1409,-7.8,1.70,0.0,0.0,Autumn,No Holiday,Yes,1434.723910
8750,30/11/2018,761,14,7.8,20,2.2,2000,-13.8,1.67,0.0,0.0,Autumn,No Holiday,Yes,695.046417
8754,30/11/2018,1384,18,4.7,34,1.9,1661,-9.8,0.00,0.0,0.0,Autumn,No Holiday,Yes,1434.723910
8757,30/11/2018,694,21,2.6,39,0.3,1968,-9.9,0.00,0.0,0.0,Autumn,No Holiday,Yes,1434.723910
8759,30/11/2018,584,23,1.9,43,1.3,1909,-9.3,0.00,0.0,0.0,Autumn,No Holiday,Yes,1434.723910

In [ ]:
dev.shape

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
sns.histplot(dev, x="Rented Bike Count")

In [ ]:
sns.histplot(preds)